# Generated by Django 4.1.5 on 2023-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'Свободно'), ('out_of_stock', 'Несвободно')], max_length=50),
        ),
    ]
